[build]

rustflags = [
  "-C",
  "target-feature=+sse2",
  "-Z",
  "new-llvm-pass-manager=no",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-Z",
  "new-llvm-pass-manager=no",
]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = [
  "-C",
  "target-feature=-crt-static",
  "-C",
  "link-arg=-lgcc",
  "-Z",
  "new-llvm-pass-manager=no",
]