name: before-publish
on: [push, pull_request]

jobs:
  check-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy

      - name: Check deny
        run: |
          cargo install cargo-deny
          cargo deny check
          cargo fmt --all -- --check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-10.15
          - windows-latest
        crate:
          - bengbenge

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Test
        shell: bash
        run: |
          cargo test --color always -p ${{ matrix.crate }}
